
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: May  6 2020 17:59:46 EDT (May  6 2020 21:59:46 UTC)

// Verification Directory fv/lfsr_behavioral 

module lfsr(clk, rst_b, seed, shift_value);
  input clk, rst_b;
  input [15:0] seed;
  output [15:0] shift_value;
  wire clk, rst_b;
  wire [15:0] seed;
  wire [15:0] shift_value;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, \shift_value[7]_109 ,
       \shift_value[8]_110 , \shift_value[9]_111 , \shift_value[10]_112
       ;
  wire \shift_value[11]_113 , \shift_value[12]_114 ,
       \shift_value[13]_115 , \shift_value[14]_116 ,
       \shift_value[15]_117 ;
  DFFSRHQX1 \shift_value_reg[15] (.RN (n_18), .SN (n_33), .CK (clk), .D
       (\shift_value[14]_116 ), .Q (\shift_value[15]_117 ));
  DFFSRHQX1 \shift_value_reg[14] (.RN (n_6), .SN (n_15), .CK (clk), .D
       (\shift_value[13]_115 ), .Q (\shift_value[14]_116 ));
  DFFSRHQX1 \shift_value_reg[13] (.RN (n_14), .SN (n_20), .CK (clk), .D
       (\shift_value[12]_114 ), .Q (\shift_value[13]_115 ));
  DFFSRHQX1 \shift_value_reg[12] (.RN (n_8), .SN (n_7), .CK (clk), .D
       (\shift_value[11]_113 ), .Q (\shift_value[12]_114 ));
  DFFSRHQX1 \shift_value_reg[11] (.RN (n_12), .SN (n_28), .CK (clk), .D
       (\shift_value[10]_112 ), .Q (\shift_value[11]_113 ));
  DFFSRHQX1 \shift_value_reg[10] (.RN (n_17), .SN (n_9), .CK (clk), .D
       (\shift_value[9]_111 ), .Q (\shift_value[10]_112 ));
  DFFSRHQX1 \shift_value_reg[9] (.RN (n_10), .SN (n_11), .CK (clk), .D
       (\shift_value[8]_110 ), .Q (\shift_value[9]_111 ));
  DFFSRHQX1 \shift_value_reg[8] (.RN (n_19), .SN (n_32), .CK (clk), .D
       (\shift_value[7]_109 ), .Q (\shift_value[8]_110 ));
  DFFSRHQX1 \shift_value_reg[7] (.RN (n_13), .SN (n_35), .CK (clk), .D
       (shift_value[6]), .Q (\shift_value[7]_109 ));
  DFFSRHQX1 \shift_value_reg[6] (.RN (n_22), .SN (n_21), .CK (clk), .D
       (shift_value[5]), .Q (shift_value[6]));
  DFFSRHQX1 \shift_value_reg[5] (.RN (n_24), .SN (n_23), .CK (clk), .D
       (shift_value[4]), .Q (shift_value[5]));
  DFFSRHQX1 \shift_value_reg[4] (.RN (n_26), .SN (n_25), .CK (clk), .D
       (shift_value[3]), .Q (shift_value[4]));
  DFFSRHQX1 \shift_value_reg[3] (.RN (n_30), .SN (n_29), .CK (clk), .D
       (shift_value[2]), .Q (shift_value[3]));
  DFFSRHQX1 \shift_value_reg[2] (.RN (n_34), .SN (n_31), .CK (clk), .D
       (shift_value[1]), .Q (shift_value[2]));
  DFFSRHQX1 \shift_value_reg[1] (.RN (n_16), .SN (n_27), .CK (clk), .D
       (shift_value[0]), .Q (shift_value[1]));
  NAND2XL g534__8780(.A (seed[7]), .B (n_5), .Y (n_35));
  OR2XL g535__4296(.A (seed[2]), .B (rst_b), .Y (n_34));
  NAND2XL g536__3772(.A (seed[15]), .B (n_5), .Y (n_33));
  NAND2XL g537__1474(.A (seed[8]), .B (n_5), .Y (n_32));
  NAND2XL g538__4547(.A (seed[2]), .B (n_5), .Y (n_31));
  OR2XL g539__9682(.A (seed[3]), .B (rst_b), .Y (n_30));
  NAND2XL g540__2683(.A (seed[3]), .B (n_5), .Y (n_29));
  NAND2XL g541__1309(.A (seed[11]), .B (n_5), .Y (n_28));
  NAND2XL g542__6877(.A (seed[1]), .B (n_5), .Y (n_27));
  OR2XL g543__2900(.A (seed[4]), .B (rst_b), .Y (n_26));
  NAND2XL g544__2391(.A (seed[4]), .B (n_5), .Y (n_25));
  OR2XL g545__7675(.A (seed[5]), .B (rst_b), .Y (n_24));
  NAND2XL g546__7118(.A (seed[5]), .B (n_5), .Y (n_23));
  OR2XL g547__8757(.A (seed[6]), .B (rst_b), .Y (n_22));
  NAND2XL g548__1786(.A (seed[6]), .B (n_5), .Y (n_21));
  NAND2XL g549__5953(.A (seed[13]), .B (n_5), .Y (n_20));
  OR2XL g550__5703(.A (seed[8]), .B (rst_b), .Y (n_19));
  OR2XL g551__7114(.A (seed[15]), .B (rst_b), .Y (n_18));
  OR2XL g552__5266(.A (seed[10]), .B (rst_b), .Y (n_17));
  OR2XL g553__2250(.A (seed[1]), .B (rst_b), .Y (n_16));
  NAND2XL g554__6083(.A (seed[14]), .B (n_5), .Y (n_15));
  OR2XL g555__2703(.A (seed[13]), .B (rst_b), .Y (n_14));
  OR2XL g556__5795(.A (seed[7]), .B (rst_b), .Y (n_13));
  OR2XL g557__7344(.A (seed[11]), .B (rst_b), .Y (n_12));
  NAND2XL g558__1840(.A (seed[9]), .B (n_5), .Y (n_11));
  OR2XL g559__5019(.A (seed[9]), .B (rst_b), .Y (n_10));
  NAND2XL g560__1857(.A (seed[10]), .B (n_5), .Y (n_9));
  OR2XL g561__9906(.A (seed[12]), .B (rst_b), .Y (n_8));
  NAND2XL g562__8780(.A (seed[12]), .B (n_5), .Y (n_7));
  OR2XL g563__4296(.A (seed[14]), .B (rst_b), .Y (n_6));
  INVX2 g564(.A (rst_b), .Y (n_5));
  DFFSRHQX1 \shift_value_reg[0] (.RN (n_0), .SN (n_1), .CK (clk), .D
       (n_4), .Q (shift_value[0]));
  CLKXOR2X1 g380__3772(.A (n_2), .B (n_3), .Y (n_4));
  XNOR2X1 g381__1474(.A (\shift_value[11]_113 ), .B
       (\shift_value[12]_114 ), .Y (n_3));
  XNOR2X1 g382__4547(.A (\shift_value[15]_117 ), .B
       (\shift_value[13]_115 ), .Y (n_2));
  NAND2BXL g383__9682(.AN (rst_b), .B (seed[0]), .Y (n_1));
  OR2XL g384__2683(.A (seed[0]), .B (rst_b), .Y (n_0));
endmodule

module prob_gen_n7(random_value, probability, prob_bit);
  input [6:0] random_value, probability;
  output prob_bit;
  wire [6:0] random_value, probability;
  wire prob_bit;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  OAI211X1 g6059__1309(.A0 (random_value[6]), .A1 (n_0), .B0 (n_13),
       .C0 (n_17), .Y (prob_bit));
  OR4X1 g6060__6877(.A (n_11), .B (n_8), .C (n_9), .D (n_16), .Y
       (n_17));
  AOI222X1 g6061__2900(.A0 (n_1), .A1 (probability[4]), .B0 (n_10), .B1
       (n_15), .C0 (n_5), .C1 (probability[3]), .Y (n_16));
  OAI22X1 g6062__2391(.A0 (n_12), .A1 (n_14), .B0 (random_value[2]),
       .B1 (n_4), .Y (n_15));
  AOI22X1 g6063__7675(.A0 (n_6), .A1 (n_7), .B0 (n_3), .B1
       (probability[1]), .Y (n_14));
  OR3X1 g6064__7118(.A (random_value[5]), .B (n_2), .C (n_9), .Y
       (n_13));
  NOR2BX1 g6065__8757(.AN (random_value[2]), .B (probability[2]), .Y
       (n_12));
  NOR2X1 g6066__1786(.A (n_1), .B (probability[4]), .Y (n_11));
  OR2X1 g6067__5953(.A (n_5), .B (probability[3]), .Y (n_10));
  NOR2BX1 g6068__5703(.AN (random_value[5]), .B (probability[5]), .Y
       (n_8));
  OR2X1 g6069__7114(.A (n_3), .B (probability[1]), .Y (n_7));
  NOR2BX1 g6070__5266(.AN (probability[0]), .B (random_value[0]), .Y
       (n_6));
  NOR2BX1 g6071__2250(.AN (random_value[6]), .B (probability[6]), .Y
       (n_9));
  INVX1 g6072(.A (random_value[3]), .Y (n_5));
  INVX1 g6073(.A (probability[2]), .Y (n_4));
  INVX1 g6074(.A (random_value[1]), .Y (n_3));
  INVX1 g6075(.A (probability[5]), .Y (n_2));
  INVX1 g6076(.A (random_value[4]), .Y (n_1));
  INVX1 g6077(.A (probability[6]), .Y (n_0));
endmodule

module lfsr_behavioral(clk, rst_b, seed, probability, prob_bit);
  input clk, rst_b;
  input [15:0] seed;
  input [7:0] probability;
  output prob_bit;
  wire clk, rst_b;
  wire [15:0] seed;
  wire [7:0] probability;
  wire prob_bit;
  wire [15:0] shift_value;
  lfsr lfsr_inst(.clk (clk), .rst_b (rst_b), .seed (seed), .shift_value
       (shift_value));
  prob_gen_n7 prob_gen_inst(.random_value (shift_value[6:0]),
       .probability (probability[6:0]), .prob_bit (prob_bit));
endmodule

